#pragma config(Sensor, S2,     choque,         sensorEV3_Touch)
#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          motor1,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor2,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Se crea un ciclo siemore verdadero que evalua constantemente el estado de dos sensores.
	while (true)
	{
		//Condicion para cuando el sensor lee el color negro.
		if ((getColorName(S3)== 1))
		{
			//Bloque de instrucciones para el color negro
			//Bloquoe de motor B y Roteacion negativa ddel motror C.
			motor [motorC]=35;
			motor [motorB]=0;
		}
 		else // if ((getColorName(S3)==6) || (getColorName(S1)== 6)) osea no negro.
 		{
			//Bloque de instrucciones para el color no negro
			//Encendido del motro B positivo a 30 e igual para el C pero a 8.
			motor [motorC]=8;
   			motor [motorB]=35;

 		}
		//Bloque para parar los motres si el Ultrasonido detecta Obstaculos.
 		if (SensorValue[choque]==1)
 		{	
			//Bloqueo de los dos motroes C y B.
   			motor [motorC]=0;
 			motor [motorB]=0;
		}
	}//Fin del While
}
