
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Se declara una variable constante para el touch sensor.
const tSensors touchSensor = (tSensors) S2;

task main()
{
/* 

   Se crea un ciclo que este leyendo continueamente el valor del touch sensor
   con el fin de realizar las aiguentes oredenes:
  
  - Touch sensor en estdo O Prender los motores C Y B en sentido (+) Hata que el Touch sensor detecte un estado 1
  - Touch sensor en estado 1 Frena motores, Gira -180, y Enciende motores en sentido (+) durante 2 seg
  -Fin.

*/

  //Si sensor no es precionado entonces avanzar positivo hasta que el estado cambie.
	while(SensorValue(touchSensor) == 0)
	{
		motor[motorC] = 100;
		motor[motorB] = 100;
	}//Fin del Ciclo.

	//Cuando se detecta que el touch sensor es diferente de 0 esperar 1s.
	//Motores Apagados durante 1seg.
	motor[motorC] = 0;
	motor[motorB] = 0;
	wait1Msec(1000);

	//Luego mover el motor C en sentido (-) mientras el B esta apagado. Durante 3seg.
	//Esta oreden hace que el EV3 gitre -180 grados Cambiando el sentido del EV3.
	motor[motorC] = -25 ;
	motor[motorB] = 0;
	wait1Msec(3000);
	//Motores Apagados durante 1 seg.
	motor[motorC] = 0;
	motor[motorB] = 0;
	wait1Msec(1000);
	// Motores Prendidos Sentido (+) durante 2seg.
	motor[motorC] = 100;
	motor[motorB] = 100;
	wait1Msec(2000);
	//Fin
}
