#pragma config(Sensor, S1,     UltraSonido,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     sencolor,       sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          izquierdo,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          derecho,       tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
		{

	if ((getColorName(S3)== 3)||(getColorName(S3)== 2) || (getColorName(S3)== 5) || (getColorName(S3)== colorBlack)|| (getColorName(S3)== colorBlack))
	{
	motor [motorC]=10;
	motor [motorB]=0;
}

 else // if ((getColorName(S3)==6) || (getColorName(S1)== 6))
 {
   motor [motorC]=0;
   motor [motorB]=10;
 }
 if (SensorValue[UltraSonido]<10)
 {
   motor [motorC]=0;
 motor [motorB]=0;
}

}

}
