

//Se ponen los parametros de los sensores
#pragma config(Sensor, S1,     UltraSonido,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     sencolor,       sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          izquierdo,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          derecho,       tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Se crea una funcion para los tonos
void sonido()
{
	//Nuestro sensor solo resive 2,6 asi que solo tiene 2 tonos.
	if(getColorName(S3)== 2){playTone(50,8);}
	if(getColorName(S3)== 3){playTone(400,8);}
	if(getColorName(S3)== 4){playTone(800,8);}
	if(getColorName(S3)>= 5){playTone(1200,8);}


}

//Inicio de la funcion Principal
task main()
{

//Creacion de un Ciclo.
	while(true)
		{
	//Implemetacion de la funcion Sonido.
		sonido();
//Condicion de lectura del sensor de color
	if ((getColorName(S3)== 3)||(getColorName(S3)== 2) || (getColorName(S3)== 5) || (getColorName(S3)== colorBlack)|| (getColorName(S3)== colorBlack))
	{
	//Mueve el motor C y deja quieto el motor B.
	motor [motorC]=16;
	motor [motorB]=0;
}

 else // if ((getColorName(S3)==6) || (getColorName(S1)== 6))
 {
  //Deja quieto el motor C y Mueve el motor B.
   motor [motorC]=0;
   motor [motorB]=16;
 }
 //Condicion cuando Hay un obstaculo a menos de 10cm del EV3.
 if (SensorValue[UltraSonido]<10)
 	{
 		//Para los motores C y B
  	 	motor [motorC]=0;
 			motor [motorB]=0;
	}

}//Fin del Ciclo

}//Fin de la tarea principal.
