#pragma config(Sensor, S1,     Ultrasonido,    sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     sencolor,       sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          izquierdo,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          derecho,       tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void sonido()
{
	if(getColorName(S3)== 3)
		{
			playTone(250, 1);

		}
		if(getColorName(S3)== 4)
		{
			playTone(400, 1);
		}
		if(getColorName(S3)== 5)
		{
			playTone(900, 1);
		}
		if(getColorName(S3)== 2)
		{
			playTone(350, 1);
		}
		if(getColorName(S3)== colorBlack)
		{
			playTone(600, 1);
		}
}


task main()
{
	while(getUSDistance(S1)<15)
	{
		sonido();

		if ((getColorName(S3)== 3)||(getColorName(S3)== 2) || (getColorName(S3)== 5) || (getColorName(S3)== colorBlack)|| (getColorName(S3)== colorBlack))
		{
			motor [motorC]=10;
			motor [motorB]=0;
		}

 		else // if ((getColorName(S3)==6) || (getColorName(S1)== 6))
 		{
   		motor [motorC]=0;
   		motor [motorB]=10;
 		}

 }
 motor [motorC]=0;
 motor [motorB]=0;

}
