#pragma config(Sensor, S1,     COLOR2,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     GIRO,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     COLOR,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ANTICHOQUE,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (1==1)
{
	if ((getColorName(S3)== 2) || (getColorName(S3)== 5) || (getColorName(S3)== colorBlack) || (getColorName(S1)== 2) || (getColorName(S1)== 5) || (getColorName(S1)== colorBlack))
{
	motor [motorC]=10;
	motor [motorB]=0;
}

 else // if ((getColorName(S3)==6) || (getColorName(S1)== 6))
 {
   motor [motorC]=0;
   motor [motorB]=10;
 }
 if (SensorValue[ANTICHOQUE]<10)
 {
   motor [motorC]=0;
 motor [motorB]=0;
}

}
}
